### ISSUE TITLE
.NET 4.8 WPF UserControl Hosted in Winform - NullReferenceException

### ISSUE THREAD

**Issue by adamrgointerject** [microsoft/dotnet-framework-early-access#62]
# Issue Title

When a WPF UserControl has a reference to the Form hosting (using ElementHost) and the UserControl tries to close the Form from a keystroke it will cause a NullReferenceException.

# Version info 
.Net Framework 4.8 (Version: 4.8.03761)
Windows 10 Pro Version 1809 (OS Build 17763.503)

# General

After installing .NET 4.8 and testing our Excel COM add-in (upgraded from .NET 4.0) with it I found that there is a bug related to a WPF UserControl being hosted in a WinForm using ElementHost. I first thought the behavior may be related to being a COM add-in rather than a desktop application, but I was able to recreate the bug with a desktop application (example solution to recreate bug is attached).

**Scenario to Cause Bug**
The below code creates a `Form` that has a `ElementHost` and shows the form:
```vb
Dim newForm As FormHostingWPF = New FormHostingWPF()
newForm.InitializeForm()
newForm.Show()
```

In FormHostingWPF.vb the `InitializeForm()` will create the WPF `UserControl` and set it to the `Form`s `ElementHost.Child` 
```vb
Friend Sub InitializeForm()
    Dim wpfControl As New WPFChild()
    wpfControl.Form = Me ' The control has a reference to Form so it can close it on button click

    ElementHost1.Child = wpfControl
End Sub
```

In `WPFChild` there is a Button and the click event is wired up to close the form hosting it. code below:
```vb
Private Sub Button_Click(sender As Object, e As Windows.RoutedEventArgs)
    If Me.Form IsNot Nothing Then Me.Form.Close()
End Sub
```

**When you press 'Tab' to give the button focus and press 'Enter' key to click the button (which closes the `Form`) the program will crash. Here is the stack trace from the exception:**
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=WindowsFormsIntegration
  StackTrace:
   at System.Windows.Forms.Integration.ElementHost.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at RecreateElementHostProcessCmdKeyBug.My.MyApplication.Main(String[] Args) in :line 81
```

**NOTE:** This exception is not thrown when using `ShowDialog()` e.g...
```vb
Using newForm As FormHostingWPF = New FormHostingWPF()
    newForm.InitializeForm()
    newForm.ShowDialog()
End Using
```

I was hoping to upgrade our application to .NET 4.8, but this bug is preventing us from committing to .NET 4.8. Is there any possible work around to this?

**Attached Solution To Recreate Bug:** [RecreateElementHostProcessCmdKeyBug.zip](https://github.com/microsoft/dotnet/files/3193110/RecreateElementHostProcessCmdKeyBug.zip)
I also reported the issue on this repo: https://github.com/microsoft/dotnet/issues/1041

**Comment by vivmishra** [comment]
@Tanya-Solyanik  @merriemcgaw 
CC: @vatsan-madhavan

**Comment by vatsan-madhavan** [comment]
When `Enter` is pressed, `S.W.Forms.Application` looks up `Control.FromChildHandleInternal(msg.hwnd)` and retrieves the previously closed `ElementHost `instance, and forwards the keypress to it. 

While this is happening, `Form.Close()` => `S.W.Forms.Form.WmClose()` is also called, which leads to the `ElementHost `being `Dispose()`'d 
    
```
        WindowsFormsIntegration.dll!System.Windows.Forms.Integration.ElementHost.Dispose(bool disposing) Line 831	C#
 	System.dll!System.ComponentModel.Component.Dispose() Line 120	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.Dispose(bool disposing) Line 6045	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Form.Dispose(bool disposing) Line 3842	C#
 	recreateelementhostprocesscmdkeybug.exe!RecreateElementHostProcessCmdKeyBug.FormHostingWPF.Dispose(Boolean disposing) Line 13	Basic
 	System.Windows.Forms.dll!System.Windows.Forms.Form.WmClose(ref System.Windows.Forms.Message m) Line 7115	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Form.WndProc(ref System.Windows.Forms.Message m) Line 7550	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m) Line 14606	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m) Line 14661	C#
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam) Line 795	C#
```
    
By the time the keypress reaches the `ElementHost`, it is no longer valid, and it throws. 

```
	WindowsFormsIntegration.dll!System.Windows.Forms.Integration.ElementHost.ProcessCmdKey(ref System.Windows.Forms.Message msg, System.Windows.Forms.Keys keyData) Line 468	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.PreProcessMessage(ref System.Windows.Forms.Message msg) Line 10163	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.PreProcessControlMessageInternal(System.Windows.Forms.Control target, ref System.Windows.Forms.Message msg) Line 10262	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(ref System.Windows.Forms.NativeMethods.MSG msg) Line 3666	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(ref System.Windows.Forms.NativeMethods.MSG msg) Line 3798	C#
```

So WinForms should either... 
  - .. not close the `ElementHost `before sending `ProcessCmdKey`, or 
  - ... not send messages to the `ElementHost `after `Close`-ing it.

**Comment by M-Lipin** [comment]
The issue has been fixed in 899206 and the fix should be available in the latest .NET 4.8.

**Comment by EngAJ** [comment]
> The issue has been fixed in 899206 and the fix should be available in the latest .NET 4.8.

When will that happen?

**Comment by merriemcgaw** [comment]
If you download [.NET 4.8](https://dotnet.microsoft.com/download/dotnet-framework/net48) you should have the fix.

**Comment by EngAJ** [comment]
> If you download [.NET 4.8](https://dotnet.microsoft.com/download/dotnet-framework/net48) you should have the fix.

This was introduced in .NET 4.8, and there isn't a new build available yet.
I downloaded again and the install fails:
.NET Framework 4.8 or a later update is already installed on this computer.

I the issue persists.

**Comment by merriemcgaw** [comment]
@M-Lipin can you please validate what update this is in?
@EngAJ - can you attach the setup logs so I can confirm precisely what you've got on your system. You can run http://aka.ms/vscollect.exe and then attach the resulting vslogs.cab (from your temp directory).

**Comment by EngAJ** [comment]
@merriemcgaw Here are the files.
[vslogs.zip](https://github.com/microsoft/dotnet-framework-early-access/files/3450470/vslogs.zip)
